# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171120_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='capacity',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post_img/'),
        ),
    ]
