# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:01
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171121_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='crop',
            field=image_cropping.fields.ImageRatioField('img', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='crop'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='post_img/'),
        ),
    ]
