# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171204_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='crop',
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post_img/'),
        ),
    ]
